version: '3.8'

services:

  frontend:
    image: frontend  # Make sure you build this image using Dockerfile
    container_name: mybooking
    ports:
      - "8082:80"  # Map host port 3000 to container port 80 (used by Nginx)
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ticketbooking

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Oracle?1
      MYSQL_DATABASE: movieticketbookingsystem
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticketbooking

  backend:
    image: backend  # Make sure you build this image using Dockerfile
    container_name: myticketbooking
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/movieticketbookingsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Oracle?1
    ports:
      - "8080:8080" 
    restart: unless-stopped
    networks:
      - ticketbooking

networks:
  ticketbooking:
    driver: bridge

volumes:
  mysql_data:
