
name: ci angular pipeline

on:
  push:
    branches: [main]
  pull:
    branches: [main, feature1, hotfix]

jobs:
  build:
  runs-on: Ubuntu-latest
  
  steps:
    - name: to checkout code
    - uses: actions/checkout@v5
