
name: ci angular pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature1, hotfix]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: to checkout code
        uses: actions/checkout@v5

    
      - name: setup node js
        uses: actions/setup-node@v5
        with:
          node-version: 17
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm ci
          npm test
        working-directory: MovieTicketBookingSystem_FrontEnd/MovieTicketBookingSystem_FrontEnd

